In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())
from queries import *

In [3]:
a = pd.read_csv('df_a.csv')
b = pd.read_csv('df_b.csv')
c = pd.read_csv('df_c.csv')
d = pd.read_csv('df_d.csv')
e = pd.read_csv('df_e.csv')
f = pd.read_csv('df_f.csv')
g = pd.read_csv('df_g.csv')
h = pd.read_csv('df_h.csv')
i = pd.read_csv('df_i.csv')
j = pd.read_csv('df_j.csv')
k = pd.read_csv('df_k.csv')
l = pd.read_csv('df_l.csv')
m = pd.read_csv('df_m.csv')

In [19]:
m

,subject_id,hadm_id,org_itemid,org_name,charttime,rownum
0,533,100009,80045,BETA STREPTOCOCCUS GROUP B,2162-05-16 21:10:00,1
1,87977,100011,80023,STAPH AUREUS COAG +,2177-09-06 18:21:00,1
2,58128,100018,80293,POSITIVE FOR METHICILLIN RESISTANT STAPH AUREUS,2176-09-02 09:04:00,1
3,9973,100020,80075,YEAST,2142-12-06 14:55:00,1
4,29971,100021,80053,ENTEROCOCCUS SP.,2109-10-04 14:18:00,1
...,...,...,...,...,...,...
20535,26198,199976,80023,STAPH AUREUS COAG +,2182-02-25 10:19:00,1
20536,25780,199988,80002,ESCHERICHIA COLI,2169-02-07 10:00:00,1
20537,20785,199993,80058,GRAM NEGATIVE ROD(S),2161-11-05 16:14:00,1
20538,23761,199994,80075,YEAST,2188-07-10 13:00:00,1
20539,19412,199995,80079,ANAEROBIC GRAM POSITIVE ROD(S),2137-12-20 17:30:00,1